## Матрицы и матричные операции. Часть 1

## Практическое задание

In [1]:
import numpy as np

__1.__ Установите, какие произведения матриц $AB$ и $BA$ определены, и найдите размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$

__Решение__<br>
a) Неопределена <br>
б) Определена, матрица 2 х 3<br>
в) Определена, матрица 8 х 8<br>
г) Определена, матрица 4 х 4<br>

__2.__ Найдите сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__Решение__<br>
$$\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}=\begin{pmatrix}
(1*4 + -2*0) & (1*(-1) + -2*5)\\ 
(3*4 + 0*0) & (3*(-1) + 0*5)
\end{pmatrix}=\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}.$$

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

__Решение__<br>
$$3\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} - 2\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} + 4\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}=\begin{pmatrix}
3*1 - 2*0 + 4*2 & 3*7-2*5-4*4\\ 
3*3 - 2*2 + 4*1 & -3*6+2*1+4*1
\end{pmatrix}=\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}.$$

In [8]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

print(f'Матрица 3A-2B+4C\n{3*A-2*B+4*C}')

Матрица 3A-2B+4C
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислите $AA^{T}$ и $A^{T}A$.

__Решение__<br>
$$A^{T} = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$$ <br>
$$AA^{T} = \begin{pmatrix}
4*4+1*1 & 4*5+1*-2 & 4*2+1*3\\ 
5*4-2*1 & 5*5-2*-2 & 5*2-2*3\\
2*4+3*1 & 2*5+3*-2 & 2*2+3*3
\end{pmatrix} =\begin{pmatrix}
17 & 18 & 11\\
18 & 29 & 4\\
11 & 4 & 13
\end{pmatrix}.$$ <br>
$$A^{T}A = \begin{pmatrix}
4*4+5*5+2*2 & 4*1+5*-2+2*3\\ 
1*4-2*5+3*2 & 1*1+2*2+3*3
\end{pmatrix} =\begin{pmatrix}
45 & 0 \\
0 & 14
\end{pmatrix}.$$

In [10]:
A = np.array([[4, 1], [5, -2], [2, 3]])
AT = A.T

print(f'Матрица A\n{A}')
print(f'Матрица AT\n{AT}')
print(f'Матрица AAT\n{A.dot(AT)}')
print(f'Матрица ATA\n{AT.dot(A)}')

Матрица A
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Матрица AT
[[ 4  5  2]
 [ 1 -2  3]]
Матрица AAT
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица ATA
[[45  0]
 [ 0 14]]


## Матрицы и матричные операции. Часть 2

## Практическое задание

__1.__ Вычислите определитель:

   a)<br>
$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$

   б) <br>  
$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$
    
   в)<br>
$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$

__Решение__:

   a)<br>
$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sin^{2}x + cos^{2}x = 1$

   б) <br>  
$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 0*\begin{vmatrix} 
2 & 3\\ 
5 & 1
\end{vmatrix} - 0*\begin{vmatrix} 
4 & 3\\ 
0 & 1
\end{vmatrix} + 9*\begin{vmatrix} 
4 & 2\\ 
0 & 5
\end{vmatrix} = 9*4*5 = 180$
    
   в)<br>
$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}= 1*\begin{vmatrix} 
5 & 6\\ 
8 & 9
\end{vmatrix} - 2*\begin{vmatrix} 
4 & 6\\ 
7 & 9
\end{vmatrix} + 3*\begin{vmatrix} 
4 & 5\\ 
7 & 8
\end{vmatrix} = 5*9-8*6-2*4*9+2*7*6+3*4*8-3*7*5 = 0$

In [19]:
A = [[np.sin(1), -np.cos(1)],[np.cos(1), np.sin(1)]]
B = [[4, 2, 3], [0, 5, 1], [0, 0, 9]]
C = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(f'Определитель матрицы A\n{np.linalg.det(A):.0f}')
print(f'Определитель матрицы B\n{np.linalg.det(B):.0f}')
print(f'Определитель матрицы C\n{np.linalg.det(C):.0f}')


Определитель матрицы A
1
Определитель матрицы B
180
Определитель матрицы C
0


__2.__ Определитель матрицы $A$ равен $4$. Найдите:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

__Решение__

   а) $det(A^{2}) = det(A) * det(A) = 16$;
    
   б) $det(A^{T}) = det(A) = 4$;
    
   в) $det(2A) = 2det(A) = 8$.

__3.__  Докажите, что матрица:

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__Решение__<br>
Матрица называется сингулярной или вырожденной, если её определитель равен нулю.<br>
$det A = \begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix} = -2*\begin{vmatrix} 
-14 & 6\\ 
7 & 13
\end{vmatrix} - 7*\begin{vmatrix} 
4 & 6\\ 
-3 & 13
\end{vmatrix} - 3*\begin{vmatrix} 
4 & -14\\ 
-3 & 7
\end{vmatrix} =$ <br>
$= 2*14*13+2*7*6-7*4*13-7*3*6-3*4*7+3*3*14 = 0$

In [20]:
C = [[-2, 7, -3], [4, -14, 6], [-3, 7, 13]]

print(f'Определитель матрицы C\n{np.linalg.det(C):.0f}')


Определитель матрицы C
0


__4.__ Найдите ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

__Решение__<br>
a)<br>
$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$<br>
Последняя строка является суммой первых двух строк. Выбросим её и вычтем из второй строки строки первую<br>
$\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2
\end{pmatrix}$<br>
Таким образом, ранг матрицы равен 2, так как минор данной матрицы невырожденный (определитель равен -4+3=-1)

In [22]:
C = [[1, 2, 3], [1, 1, 1], [2, 3, 4]]

print(f'Ранг матрицы \n{np.linalg.matrix_rank(C):.0f}')

Ранг матрицы 
2


б)<br>
$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$<br>
Третья строка является суммой первых двух, значит её можно удалить. Последнюю строку можно переставить на первую строчку <br>
$\begin{pmatrix}
2 & 3 & 5 & 6\\
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2
\end{pmatrix}.$<br>
Таким образом, ранг матрицы равен 3, так как минор данной матрицы невырожденный (определитель равен 3(4-2)=6)

In [23]:
C = [[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 5]]

print(f'Ранг матрицы \n{np.linalg.matrix_rank(C):.0f}')

Ранг матрицы 
3
