# Линейные преобразования

__1.__ Найдите собственные векторы и собственные значения для линейного оператора, заданного матрицей:

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

__Решение__:

$$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix}=0$$

$$(-1-\lambda)(6-\lambda)+6*2=0$$
$$-6-5\lambda+\lambda^{2}+12=0$$
$$\lambda^{2}-5\lambda+6=0$$
$$\lambda_{1}=2$$
$$\lambda_{2}=3$$
Собственные значения равны 2 и 3
<br><br>
$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda_{1}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

$$\begin{cases}
-x_{1}-6x_{2}= 2x_{1}, \\
2x_{1}+6x_{2}= 2x_{2}
\end{cases} = 
\begin{cases}
x_{1}=-2x_{2}
\end{cases}$$
Приняв $x_{2}=1$ получим $x_{1}=-2$
$$x=x_{2}*\begin{pmatrix}
-2\\ 
1
\end{pmatrix}$$
<br><br>
$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda_{2}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

$$\begin{cases}
-x_{1}-6x_{2}= 3x_{1}, \\
2x_{1}+6x_{2}= 3x_{2}
\end{cases} = 
\begin{cases}
x_{1}=-1.5x_{2}= 0
\end{cases}$$
Приняв $x_{2}=1$ получим $x_{1}=-1.5$
$$x=x_{2}*\begin{pmatrix}
-1.5\\ 
1
\end{pmatrix}$$

In [9]:
import numpy as np

a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей:

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$
Покажите, что __любой__ вектор считается для него собственным.

__Решение__:

$$\begin{vmatrix}
-1-\lambda & 0\\ 
0 & -1-\lambda
\end{vmatrix}=0$$
$$(-1-\lambda)^{2}=0$$
$$\lambda=-1$$
<br>
$$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$
$$\begin{cases}
-x_{1}= -x_{1}, \\
-x_{2}= -x_{2}
\end{cases}$$
Система уравнений имеет неопределённое количество корней, следовательно любой вектор является собственным для данного оператора

In [10]:
import numpy as np

a = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


__3.__ Пусть линейный оператор задан матрицей:

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установите, считается ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

__Решение__:

$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}.
$$
$$\begin{cases}
1+1= \lambda, \\
-1+3= \lambda
\end{cases}$$
$$\lambda=2$$
Вектор $x=(1,1)$ является собственным вектором этого линейного оператора

In [11]:
import numpy as np

a = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2. 2.]
Собственные векторы:
[[ 0.71 -0.71]
 [ 0.71 -0.71]]


**4.** Пусть линейный оператор задан матрицей:

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установите, считается ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

__Решение__:

$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\ 
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\ 
-3\\ 
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\ 
-3\\ 
-4
\end{pmatrix}.
$$
$$\begin{cases}
3*-3= 3\lambda, \\
3*3= -3\lambda, \\
3*-4= -4\lambda, \\
\end{cases}$$
$$\lambda=3$$

Вектор $x=(3, -3, -4)$ является собственным вектором этого линейного оператора